### ISSUE TITLE
(Task) Implement minimum sizes for the create account route.

### ISSUE THREAD

**Issue by Dylan-Gresham** [Dylan-Gresham/BookTrack#44]
References user story #1 

There should be a minimum size that the create account route supports. I'm thinking of making this minimum be the size of an iPhone SE.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the CSS to ensure the create account page has a minimum width and height that matches the dimensions of an iPhone SE (320x568px). Added media queries to adjust styling for smaller screens.

You can review changes in this commit: https://github.com/lattaai13/Dylan-Gresham-BookTrack-44/commit/d8fc8e25129e251e053d896d43067fb70402c707.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
